apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        # Replace below line for gcr or docker hub accordingly
        image: mangesh98/myapp:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8888
        env:
          - name: PORT
            value: "8888"
